services:
  web:
    environment:
      - DJANGO_DEBUG=False
      - GRAPHDB_HOST=http://graphdb:7200/
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn project_django.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    restart: unless-stopped

  graphdb:
    environment:
      - GDB_HEAP_SIZE=8g
      - GDB_JAVA_OPTS=-Djava.awt.headless=true
    restart: unless-stopped

  # Optional: Nginx reverse proxy untuk production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/var/www/static:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - marvel-dc-network 